# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27f65afb0792bd029cccb7695e5037e9297b76fc364d19cc417e38639be083d4bbc427f7e2607973c36d20264d3c0d35fed1d6000b8079e2290600991a5e3053

test:
  secret_key_base: 136f1d7b513790b79ec46b4bb683def571817ca59cc6e99d42c62b63a9aa23a599d1e86d8bff7f67bc260f1793324b9660bcfc67b9616a291409db4181dc0812

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
